name: CI core

on:
  workflow_call:
    inputs:
      language:
        required: true
        type: string
    secrets:
      ANTHROPIC_API_KEY:
        required: false
      CODECOV_TOKEN:
        required: false

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "language is ${{ inputs.language }}"
